import configs from '@tsparticles/configs'
import { bundleControls, defaultControls } from './controls'

function baseDemo({
  id,
  categoryId,
  label,
  description,
  configKey,
  controls = defaultControls,
  features = [],
  optionOverrides,
}) {
  return {
    id,
    categoryId,
    label,
    description,
    controls,
    features,
    mode: 'engine',
    options: configs[configKey],
    optionOverrides,
  }
}

export const demos = [
  baseDemo({
    id: 'ambient',
    categoryId: 'presets',
    label: 'Ambient',
    description: 'ゆったり漂う ambient 系 background。',
    configKey: 'basic',
    features: ['ambient', 'soft'],
    optionOverrides: {
      background: { color: '#0f172a' },
      particles: {
        color: { value: ['#a78bfa', '#67e8f9', '#f8fafc'] },
        opacity: { value: 0.45 },
        move: { speed: 1 },
        links: { enable: true, opacity: 0.2 },
      },
    },
  }),
  baseDemo({
    id: 'basic',
    categoryId: 'presets',
    label: 'Basic',
    description: '最小構成の particles background。',
    configKey: 'basic',
    features: ['links', 'background'],
  }),
  baseDemo({
    id: 'big-circles',
    categoryId: 'presets',
    label: 'Big Circles',
    description: '大きな circle が漂う preset 系。',
    configKey: 'big',
    features: ['big', 'circles'],
  }),
  baseDemo({
    id: 'bubbles-preset',
    categoryId: 'presets',
    label: 'Bubbles',
    description: 'bubble interaction と丸粒子の組み合わせ。',
    configKey: 'bubble',
    features: ['bubbles', 'interaction'],
  }),
  baseDemo({
    id: 'confetti-preset',
    categoryId: 'presets',
    label: 'Confetti',
    description: 'confetti らしいカラフルな preset。',
    configKey: 'fallingConfetti',
    features: ['confetti', 'celebration'],
    optionOverrides: {
      particles: {
        move: { speed: 3 },
      },
    },
  }),
  baseDemo({
    id: 'confetti-cannon',
    categoryId: 'presets',
    label: 'Confetti Cannon',
    description: '中央から打ち上がる confetti cannon 風。',
    configKey: 'confettiExplosions',
    features: ['confetti', 'cannon'],
  }),
  baseDemo({
    id: 'snow',
    categoryId: 'presets',
    label: 'Snow',
    description: 'ゆっくり落ちる snow preset 系。',
    configKey: 'snow',
    features: ['falling', 'winter'],
  }),
  baseDemo({
    id: 'fire',
    categoryId: 'presets',
    label: 'Fire',
    description: '炎のような warm color particles。',
    configKey: 'fireworks3',
    features: ['fire', 'warm'],
    optionOverrides: {
      background: { color: '#140a06' },
      particles: {
        move: { speed: 1.8 },
      },
    },
  }),
  baseDemo({
    id: 'firefly',
    categoryId: 'presets',
    label: 'Firefly',
    description: '夜の firefly 風の発光表現。',
    configKey: 'star',
    features: ['firefly', 'glow'],
    optionOverrides: {
      background: { color: '#08131f' },
      particles: {
        links: { enable: false },
        move: { speed: 1.1 },
        color: { value: ['#fde68a', '#fef08a', '#86efac'] },
      },
    },
  }),
  baseDemo({
    id: 'sea-anemone',
    categoryId: 'presets',
    label: 'Sea Anemone',
    description: '有機的なゆらぎが見える preset。',
    configKey: 'seaAnemone',
    features: ['organic', 'ambient'],
  }),
  baseDemo({
    id: 'fountain-preset',
    categoryId: 'presets',
    label: 'Fountain',
    description: '下から噴き上がる fountain 風 preset。',
    configKey: 'emitter',
    features: ['fountain', 'emitter'],
    optionOverrides: {
      background: { color: '#071226' },
    },
  }),
  baseDemo({
    id: 'hyperspace',
    categoryId: 'presets',
    label: 'Hyperspace',
    description: '高速移動で奥行き感が強い preset。',
    configKey: 'hyperspace',
    features: ['depth', 'speed'],
  }),
  baseDemo({
    id: 'links',
    categoryId: 'presets',
    label: 'Links',
    description: '線でつながる定番 links background。',
    configKey: 'basic',
    features: ['links', 'network'],
    optionOverrides: {
      particles: {
        links: { enable: true, opacity: 0.4, distance: 150 },
      },
    },
  }),
  baseDemo({
    id: 'stars',
    categoryId: 'presets',
    label: 'Stars',
    description: '宇宙感のある星空 preset。',
    configKey: 'star',
    features: ['stars', 'space'],
  }),
  baseDemo({
    id: 'fireworks-config',
    categoryId: 'presets',
    label: 'Fireworks Config',
    description: 'config ベースの fireworks 表現。',
    configKey: 'fireworks',
    features: ['explosions', 'burst'],
  }),
  baseDemo({
    id: 'squares',
    categoryId: 'presets',
    label: 'Squares',
    description: 'square 粒子を前面にした preset。',
    configKey: 'matrix',
    features: ['squares', 'shape'],
    optionOverrides: {
      particles: {
        shape: { type: 'square' },
        move: { speed: 2.2 },
      },
    },
  }),
  baseDemo({
    id: 'falling-confetti',
    categoryId: 'presets',
    label: 'Falling Confetti',
    description: '紙吹雪が落ち続ける preset 系。',
    configKey: 'fallingConfetti',
    features: ['confetti', 'gravity'],
  }),
  baseDemo({
    id: 'matrix',
    categoryId: 'presets',
    label: 'Matrix',
    description: 'デジタル感の強い matrix 系 config。',
    configKey: 'matrix',
    features: ['matrix', 'tech'],
  }),
  baseDemo({
    id: 'triangles',
    categoryId: 'presets',
    label: 'Triangles',
    description: 'triangle 系 particles の preset。',
    configKey: 'triangles',
    features: ['triangles', 'shape'],
  }),
  baseDemo({
    id: 'shape-arrow',
    categoryId: 'shapes',
    label: 'Arrow',
    description: 'arrow shape の見え方を確認。',
    configKey: 'shapeArrow',
    features: ['shape'],
  }),
  baseDemo({
    id: 'shape-cards',
    categoryId: 'shapes',
    label: 'Card',
    description: 'card shape の見え方を確認。',
    configKey: 'cards',
    features: ['shape', 'card'],
  }),
  baseDemo({
    id: 'shape-image',
    categoryId: 'shapes',
    label: 'Image',
    description: 'image shape の見え方を確認。',
    configKey: 'images',
    features: ['shape', 'image'],
  }),
  baseDemo({
    id: 'shape-line',
    categoryId: 'shapes',
    label: 'Line / Polygon',
    description: 'line と polygon 系の形状差を確認。',
    configKey: 'polygons',
    features: ['shape', 'line', 'polygon'],
  }),
  baseDemo({
    id: 'shape-cog',
    categoryId: 'shapes',
    label: 'Cog',
    description: 'cog shape の見え方を確認。',
    configKey: 'shapeCog',
    features: ['shape'],
  }),
  baseDemo({
    id: 'shape-emoji',
    categoryId: 'shapes',
    label: 'Emoji',
    description: 'emoji shape の見え方を確認。',
    configKey: 'shapeEmoji',
    features: ['shape', 'emoji'],
  }),
  baseDemo({
    id: 'shape-heart',
    categoryId: 'shapes',
    label: 'Heart',
    description: 'heart shape の見え方を確認。',
    configKey: 'shapeHeart',
    features: ['shape'],
  }),
  baseDemo({
    id: 'shape-rounded-rect',
    categoryId: 'shapes',
    label: 'Rounded Rect',
    description: 'rounded-rect shape の見え方を確認。',
    configKey: 'shapeRoundedRect',
    features: ['shape'],
  }),
  baseDemo({
    id: 'shape-rounded-polygon',
    categoryId: 'shapes',
    label: 'Rounded Polygon',
    description: 'rounded-polygon shape の見え方を確認。',
    configKey: 'shapeRoundedPolygon',
    features: ['shape'],
  }),
  baseDemo({
    id: 'shape-spiral',
    categoryId: 'shapes',
    label: 'Spiral Shape',
    description: 'spiral shape の見え方を確認。',
    configKey: 'shapeSpiral',
    features: ['shape'],
  }),
  baseDemo({
    id: 'shape-squircle',
    categoryId: 'shapes',
    label: 'Squircle',
    description: 'squircle shape の見え方を確認。',
    configKey: 'shapeSquircle',
    features: ['shape'],
  }),
  baseDemo({
    id: 'shape-path',
    categoryId: 'shapes',
    label: 'Path Shape',
    description: 'path shape の見え方を確認。',
    configKey: 'shapePath',
    features: ['shape', 'path-shape'],
  }),
  baseDemo({
    id: 'shape-text',
    categoryId: 'shapes',
    label: 'Multiline Text',
    description: 'text / multiline text shape の見え方を確認。',
    configKey: 'shapeMultilineText',
    features: ['shape', 'text'],
  }),
  baseDemo({
    id: 'absorbers',
    categoryId: 'plugins',
    label: 'Absorbers',
    description: '吸い込み plugin の標準デモ。',
    configKey: 'absorbers',
    features: ['absorber'],
  }),
  baseDemo({
    id: 'emitter',
    categoryId: 'plugins',
    label: 'Emitter',
    description: 'emitters plugin の標準デモ。',
    configKey: 'emitter',
    features: ['emitter'],
  }),
  baseDemo({
    id: 'emitter-absorber',
    categoryId: 'plugins',
    label: 'Emitter + Absorber',
    description: '発生源と吸収体の組み合わせ。',
    configKey: 'emitterAbsorber',
    features: ['emitter', 'absorber'],
  }),
  baseDemo({
    id: 'polygon-mask',
    categoryId: 'plugins',
    label: 'Polygon Mask',
    description: 'polygon mask plugin を使う構成。',
    configKey: 'polygonMask',
    features: ['polygon-mask'],
  }),
  baseDemo({
    id: 'bubble',
    categoryId: 'plugins',
    label: 'Bubble Interaction',
    description: 'hover bubble interaction の挙動を確認。',
    configKey: 'bubble',
    features: ['interaction', 'bubble'],
  }),
  baseDemo({
    id: 'repulse',
    categoryId: 'plugins',
    label: 'Repulse Interaction',
    description: 'repulse interaction の標準挙動。',
    configKey: 'repulse',
    features: ['interaction', 'repulse'],
  }),
  baseDemo({
    id: 'light-hover',
    categoryId: 'plugins',
    label: 'Light Hover',
    description: 'light hover 系 interaction。',
    configKey: 'lightHover',
    features: ['interaction', 'light'],
  }),
  baseDemo({
    id: 'mouse-trail',
    categoryId: 'plugins',
    label: 'Mouse Trail',
    description: 'マウス軌跡を使った interaction。',
    configKey: 'mouseTrail',
    features: ['interaction', 'trail'],
  }),
  baseDemo({
    id: 'mouse-cannon',
    categoryId: 'plugins',
    label: 'Mouse Cannon',
    description: 'mouse cannon interaction の表現。',
    configKey: 'mouseCannon',
    features: ['interaction', 'cannon'],
  }),
  baseDemo({
    id: 'infection',
    categoryId: 'plugins',
    label: 'Infection',
    description: '感染のように広がる plugin デモ。',
    configKey: 'infection',
    features: ['plugin', 'infection'],
  }),
  baseDemo({
    id: 'path-brownian',
    categoryId: 'paths-effects',
    label: 'Brownian Path',
    description: 'Brownian path generator の動き。',
    configKey: 'pathBrownian',
    features: ['path'],
  }),
  baseDemo({
    id: 'path-grid',
    categoryId: 'paths-effects',
    label: 'Grid Path',
    description: 'grid path generator の動き。',
    configKey: 'pathGrid',
    features: ['path'],
  }),
  baseDemo({
    id: 'path-spiral',
    categoryId: 'paths-effects',
    label: 'Spiral Path',
    description: 'spiral path generator の動き。',
    configKey: 'pathSpiral',
    features: ['path'],
  }),
  baseDemo({
    id: 'path-zigzag',
    categoryId: 'paths-effects',
    label: 'ZigZag Path',
    description: 'zig-zag path generator の動き。',
    configKey: 'pathZigZag',
    features: ['path'],
  }),
  baseDemo({
    id: 'effect-bubble',
    categoryId: 'paths-effects',
    label: 'Effect Bubble',
    description: 'effect bubble の見え方。',
    configKey: 'effectBubble',
    features: ['effect'],
  }),
  baseDemo({
    id: 'effect-particles',
    categoryId: 'paths-effects',
    label: 'Effect Particles',
    description: 'effect particles の見え方。',
    configKey: 'effectParticles',
    features: ['effect'],
  }),
  baseDemo({
    id: 'effect-trail',
    categoryId: 'paths-effects',
    label: 'Effect Trail',
    description: 'effect trail の見え方。',
    configKey: 'effectTrail',
    features: ['effect', 'trail'],
  }),
  baseDemo({
    id: 'gradients',
    categoryId: 'palettes',
    label: 'Gradients',
    description: 'palette / gradient 系の色味を確認。',
    configKey: 'gradients',
    features: ['palette', 'color'],
  }),
  baseDemo({
    id: 'named-colors',
    categoryId: 'palettes',
    label: 'Named Colors',
    description: 'named color 系 palette/config。',
    configKey: 'namedColors',
    features: ['palette', 'color'],
  }),
  baseDemo({
    id: 'style',
    categoryId: 'palettes',
    label: 'Style',
    description: 'style / palette 系の見え方を確認。',
    configKey: 'style',
    features: ['palette', 'style'],
  }),
  {
    id: 'bundle-particles',
    categoryId: 'bundles',
    label: 'Particles API',
    description: 'focused `particles()` API で作るシンプル背景。',
    mode: 'particles-api',
    controls: bundleControls,
    features: ['bundle', 'particles-api'],
    config: {
      count: 120,
      speed: 2,
      size: 3,
      colors: ['#38bdf8', '#a78bfa', '#f8fafc'],
      background: '#0b1020',
      links: true,
      linksColor: '#a78bfa',
      opacity: 0.75,
    },
  },
  {
    id: 'bundle-confetti',
    categoryId: 'bundles',
    label: 'Confetti API',
    description: 'focused `confetti()` API で作る祝祭演出。',
    mode: 'confetti-api',
    controls: bundleControls,
    features: ['bundle', 'confetti'],
    config: {
      count: 70,
      speed: 3,
      size: 4,
      colors: ['#f472b6', '#facc15', '#22d3ee', '#34d399'],
      background: '#20103f',
    },
  },
  {
    id: 'bundle-fireworks',
    categoryId: 'bundles',
    label: 'Fireworks API',
    description: 'focused `fireworks()` API で作る打ち上げ演出。',
    mode: 'fireworks-api',
    controls: bundleControls,
    features: ['bundle', 'fireworks'],
    config: {
      count: 60,
      speed: 4,
      size: 5,
      colors: ['#fb7185', '#facc15', '#38bdf8', '#c084fc'],
      background: '#12051f',
    },
  },
]
